# Generated by Django 3.0.4 on 2020-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
