# Generated by Django 3.0.4 on 2020-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_doctor_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='anything to add?'),
        ),
    ]
