# Generated by Django 3.0.4 on 2020-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_doctor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='utc_offset',
            field=models.IntegerField(default=0),
        ),
    ]
