# Generated by Django 3.0.4 on 2020-03-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20200325_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='feedback_response',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No, there was a technical problem'), (2, 'No, there was a problem with the volunteer')], default=0, verbose_name='did everything go well?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='feedback_text',
            field=models.TextField(blank=True, verbose_name='any feedback for us?'),
        ),
    ]
