# Generated by Django 3.0.4 on 2020-03-26 06:15

import clinic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('clinic', '0010_auto_20200326_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='credentials',
            field=models.FileField(blank=True, null=True, upload_to=clinic.models.upload_filename),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='self_certification_questions',
            field=models.ManyToManyField(blank=True, to='clinic.SelfCertificationQuestion'),
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
