# Generated by Django 3.0.4 on 2020-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20200326_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='last_online',
            new_name='last_seen',
        ),
        migrations.AddField(
            model_name='patient',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='notify',
            field=models.BooleanField(default=True, help_text='Not yet implemented', verbose_name='send notifications'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='verified',
            field=models.BooleanField(default=False, help_text='Allows the provider to receive calls.', verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
