# Generated by Django 3.0.4 on 2020-03-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20200328_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
