# Generated by Django 3.0.4 on 2020-03-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_volunteerupdate'),
        ('clinic', '0017_doctor_provider_type'),
    ]

    operations = [
    ]
