# Generated by Django 3.0.4 on 2020-03-29 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_merge_20200329_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerupdate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
