# Generated by Django 3.0.4 on 2020-03-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_volunteerupdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
