# Generated by Django 3.0.4 on 2020-04-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_auto_20200330_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('room-created', 'room created'), ('room-ended', 'room ended'), ('participant-connected', 'participant connected'), ('participant-disconnected', 'participant disconnected'), ('track-added', 'track added'), ('track-removed', 'track removed')], max_length=50)),
                ('room_name', models.CharField(max_length=254)),
                ('room_status', models.CharField(choices=[('in-progress', 'in progress'), ('failed', 'failed'), ('completed', 'completed')], max_length=20)),
                ('room_duration', models.DurationField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('participant_status', models.CharField(blank=True, choices=[('connected', 'connected'), ('disconnected', 'disconnected')], max_length=20)),
                ('participant_id', models.CharField(blank=True, max_length=254)),
                ('participant_duration', models.DurationField(blank=True, null=True)),
                ('track_kind', models.CharField(blank=True, choices=[('data', 'data'), ('audio', 'audio'), ('video', 'video')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='provider_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Other'), (2, 'Doctor'), (3, 'Nurse'), (4, 'Student')], default=0, help_text='Doctor, nurse or student', verbose_name='provider type'),
        ),
    ]
