# Generated by Django 3.0.4 on 2020-04-04 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_auto_20200404_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsummary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='summary created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callsummary',
            name='first_event',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='summary last updated'),
        ),
    ]
